rules:
  quote-props: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/no-extraneous-dependencies: off
  import/no-webpack-loader-syntax: off
  import/no-unresolved: off
  import/extensions: off
  react/jsx-filename-extension: off
  react/prop-types: off
env:
  shared-node-browser: true
